language: csharp
solution: ProjectBlackmagic.RestfulClient.sln

mono: none
dotnet: 1.1.6
dist: trusty
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./test/ProjectBlackmagic.RestfulClient.Test.csproj

matrix:
  include:
    - dotnet: 1.1.6
      mono: none
      dist: trusty
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest